center_screen = windower.get_windower_settings().x_res / 2 - 500 / 2

unitframe_text_defaults = {}
unitframe_text_defaults.pos = {}
unitframe_text_defaults.pos.x = center_screen
unitframe_text_defaults.pos.y = 50
unitframe_text_defaults.text = {}
unitframe_text_defaults.text.size = 12
unitframe_text_defaults.text.font = 'Late'
unitframe_text_defaults.text.fonts = {'Lato', 'Trebuchet MS'}
unitframe_text_defaults.text.stroke = {}
unitframe_text_defaults.text.stroke.width = 2
unitframe_text_defaults.text.stroke.alpha = 220
unitframe_text_defaults.text.stroke.red = 0
unitframe_text_defaults.text.stroke.green = 0
unitframe_text_defaults.text.stroke.blue = 0
unitframe_text_defaults.flags = {}
unitframe_text_defaults.flags.italic = false
unitframe_text_defaults.flags.bold = true
unitframe_text_defaults.flags.draggable = false
unitframe_text_defaults.bg = {}
unitframe_text_defaults.bg.visible = false

unitframe_image_defaults = {}
unitframe_image_defaults.pos = {}
unitframe_image_defaults.pos.x = center_screen
unitframe_image_defaults.pos.y = 50
unitframe_image_defaults.visible = true
unitframe_image_defaults.color = {}
unitframe_image_defaults.color.alpha = 255
unitframe_image_defaults.color.red = 255
unitframe_image_defaults.color.green = 0
unitframe_image_defaults.color.blue = 0
unitframe_image_defaults.size = {}
unitframe_image_defaults.size.width = 1
unitframe_image_defaults.size.height = 50
unitframe_image_defaults.texture = {}
unitframe_image_defaults.texture.fit = true
unitframe_image_defaults.repeatable = {}
unitframe_image_defaults.repeatable.x = 1
unitframe_image_defaults.repeatable.y = 1
unitframe_image_defaults.draggable = false